<a href="https://colab.research.google.com/github/lifehyun/ai/blob/%2Bpython/07%ED%8C%90%EB%8B%A4%EC%8A%A4%EC%98%88%EC%A0%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%842(%ED%95%84%ED%84%B0%EB%A7%81).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd



data = [
    ["037730", "3R", 1510, 7.36],
    ["036360", "3SOFT", 1790, 1.65],
    ["005760", "ACTS", 1185, 1.28],
]
columns = ["종목코드", "종목명", "현재가", "등락률"]
df = pd.DataFrame(data=data, columns=columns)
df.set_index('종목코드', inplace=True)
df
# 1.  현재가가 1500 이상인 값만
df[ df['현재가']   >= 1500  ]
# 2.  현재가가 1,500원 이상이면서 1,700원 미만인 값
cond = ( df[ '현재가' ] >= 1500  )  & ( df[ '현재가' ] < 1700  )
df[  cond  ]
df
# 3. 열을 추가하기 목표가 컬럼을 추가
df['목표가'] = df['현재가'] * 0.01
df
# 4. 행을 추가
df.loc['066570'] = ['LG전자', 60000, 3.84, 60000*0.01 ]
# df.loc[인덱스번호] = ['값들 ]
df

df.loc[  '037730' ]  # '037730' 인덱스의 행의 정보를 보여준다

# 6. 컬럼명 변경 (columns 속성)
df5 = pd.DataFrame(data = [[1, 2, 3], [4, 5, 6]], columns=["A", "B", "C"])
df5
#  컬럼명을 'a', 'b', 'c'로 변경
df5.columns =  ['a', 'b', 'c' ]  # 방법1
df5
df5.rename( columns={ 'a': '가' , 'b':'나', 'c':'다'  }, inplace=True )  # 방법2
df5
# 7.
import numpy as np
data = {"카카오": [ np.nan, 221, 35], "NAVER": [52, 47, 3]}
index = [2019, 2020, 2021]
df7 = pd.DataFrame(data=data, index=index)
df7
df7.index.dtype
df7.columns.name
df7.index.name = 'year'  # 익덱스의 열들의 이름을 부여하는 것 엑셀에서 블록이름과 비슷함
df7.columns.name = 'company'
df7.index.name
df7.columns.name
df7
# 8.
data = {"카카오": [np.nan, 221, 35], "NAVER": [52, 47, 3]}
index = [2019, 2020, 2021]
df8 = pd.DataFrame(data=data, index=index)
df8

# 9. 데이터프레임 drop  '카카오'와 'NAVER' 컬럼을 삭제
df8.drop( '카카오', axis= 1  )
df8.drop( 'NAVER', axis= 1  )
df8.drop(  [ '카카오', 'NAVER' ]  , axis=1)
# 10
data = [
    [1, 2, 3],
    [np.nan, 5, 6],
    [7, np.nan, 9],
    [10, 11, np.nan]
]
df10 = pd.DataFrame(data)
df10
# np.nan 값이 있는 모든 행을 제거
df10.dropna()

# 11
data = [
    [1, 1, np.nan],
    [10, np.nan, 10],
    [2, 3, 4]
]
columns = ['col0', 'col1', 'col2']
df11 = pd.DataFrame(data, columns=columns)
df11
# 문제  col2 컬럼의 값에 NaN이 포함된 행만 제거
df11.dropna( subset = 'col2' )
# 12   NaN 값을 0으로 채우기
df12 = df11.fillna( 0 )
# 13 replace  0을 100으로 변경
df12.replace( 0, 100  )

# 14
data = [
    {"cd":"A060310", "nm":"3S", "open":2920, "close":2800},
    {"cd":"A095570", "nm":"AJ네트웍스", "open":1920, "close":1900},
    {"cd":"A006840", "nm":"AK홀딩스", "open":2020, "close":2010},
    {"cd":"A054620", "nm":"APS홀딩스", "open":3120, "close":3200}
]
df14 = pd.DataFrame(data=data)
df14 = df14.set_index('cd')
df14
# 종가(close)가 시가(open)보다 큰 데이터만 가져오기
df14.query( 'open  <  close '   )
# 15  종가(close)가 3,000원 이상인 종목만 출력
df14.query( 'close >= 3000' )
# 16  시가(open)가 2,000원 이상이고 종가(close)가 시가(open)이상인 종목
df14.query( 'open >=2000 and close >= open')
# 17.  종목명(nm)이 'A'로 시작하는 종목만 ??
# cond=df14[ 'nm'].str[ :1 ]
df14.query(     "nm.str.startswith('A')"   )
# 18. 종목명에 '홀딩스'가 포함된 종목만
df14.query( "nm.str.contains('홀딩스')" )
# 19.
data = {
    "PER": [6.42, 17.63, 21.09, 13.93],
    "PBR": [1.10, 1.49, 2.06, 1.88],
    "DPS": [1416, 1716, 2994, 1755]
}
index = ["2019/12", "2020/12", "2021/12", "2022/12(E)"]
df19 = pd.DataFrame(data=data, index=index)
# df19[ ['PER', 'PBR'] ]
#  20 PER'과 'PBR' 컬럼을 선택
df19.filter( items=[  'PER', 'PBR' ] , axis=1 )
# 21 filter 메서드를 사용해서 예상치인 '2022/12(E)'를 제외한 나머지 로우 데이터를 선택
df19.filter(  regex='12$', axis=0  )
# 22  "2022"년 데이터만 선택
df19.filter(  like='2022', axis = 0 )

              PER   PBR   DPS
2022/12(E)  13.93  1.88  1755